# on: [push, pull_request]

name: ci
on: push
env:
  go-version: '1.26.x'
defaults:
  run:
    shell: sh
jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Go ${{ env.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.go-version }}

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Build
      run: go build ./...

    - name: Test
      run: go test --cover ./...

    - name: vet
      run: go vet ./...

    - name: staticcheck
      if: matrix.os == 'ubuntu-latest'
      # @v1.4.1
      uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431
      with:
        # 2026.1
        version: ff63afafc529279f454e02f1d060210bd4263951
        install-go: false
